### ISSUE TITLE
Semantic convention table generation is broken

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-specification#1579]
```
$ make table-generation
docker run --rm -v /Users/jbd/opentelemetry-specification/semantic_conventions:/source -v /Users/jbd/opentelemetry-specification/specification:/spec otel/semconvgen -f /source markdown -md /spec
Using default SPAN type for semantic convention 'cloud' @ line 5
Using default SPAN type for semantic convention 'aws.ecs' @ line 5
Using default SPAN type for semantic convention 'aws.eks' @ line 5
Using default SPAN type for semantic convention 'aws.log' @ line 5
Using default SPAN type for semantic convention 'container' @ line 5
Using default SPAN type for semantic convention 'deployment' @ line 5
Using default SPAN type for semantic convention 'faas_resource' @ line 5
Error parsing /source/resource/faas.yaml

Invalid type: int is not allowed - @38:9
Using default SPAN type for semantic convention 'host' @ line 5
Using default SPAN type for semantic convention 'k8s.cluster' @ line 5
Using default SPAN type for semantic convention 'k8s.node' @ line 5
Using default SPAN type for semantic convention 'k8s.namespace' @ line 5
Using default SPAN type for semantic convention 'k8s.pod' @ line 5
Using default SPAN type for semantic convention 'k8s.container' @ line 5
Using default SPAN type for semantic convention 'k8s.replicaset' @ line 5
Using default SPAN type for semantic convention 'k8s.deployment' @ line 5
Using default SPAN type for semantic convention 'k8s.statefulset' @ line 5
Using default SPAN type for semantic convention 'k8s.daemonset' @ line 5
Using default SPAN type for semantic convention 'k8s.job' @ line 5
Using default SPAN type for semantic convention 'k8s.cronjob' @ line 5
Using default SPAN type for semantic convention 'os' @ line 5
Using default SPAN type for semantic convention 'process' @ line 5
Error parsing /source/resource/process.yaml

Invalid type: int is not allowed - @8:9
Using default SPAN type for semantic convention 'service' @ line 5
Using default SPAN type for semantic convention 'telemetry' @ line 5
Using default SPAN type for semantic convention 'db' @ line 7
Using default SPAN type for semantic convention 'db.mssql' @ line 7
Using default SPAN type for semantic convention 'db.cassandra' @ line 7
Error parsing /source/trace/database.yaml

Invalid type: int is not allowed - @261:11
Using default SPAN type for semantic convention 'exception' @ line 5
Using default SPAN type for semantic convention 'faas_span' @ line 5
Using default SPAN type for semantic convention 'faas_span.datasource' @ line 5
Using default SPAN type for semantic convention 'faas_span.http' @ line 5
Using default SPAN type for semantic convention 'faas_span.pubsub' @ line 5
Using default SPAN type for semantic convention 'faas_span.timer' @ line 5
Using default SPAN type for semantic convention 'faas_span.in' @ line 5
Using default SPAN type for semantic convention 'faas_span.out' @ line 5
Using default SPAN type for semantic convention 'network' @ line 5
Error parsing /source/trace/general.yaml

Invalid type: int is not allowed - @44:9
Using default SPAN type for semantic convention 'http' @ line 5
Error parsing /source/trace/http.yaml

Invalid type: int is not allowed - @38:9
Using default SPAN type for semantic convention 'messaging' @ line 7
Error parsing /source/trace/messaging.yaml

Invalid type: int is not allowed - @61:11
Using default SPAN type for semantic convention 'rpc' @ line 7
Using default SPAN type for semantic convention 'rpc.grpc' @ line 7
Traceback (most recent call last):
  File "/usr/local/bin/gen-semconv", line 33, in <module>
    sys.exit(load_entry_point('semconvgen==0.2.0', 'console_scripts', 'gen-semconv')())
  File "/usr/local/lib/python3.8/site-packages/semconvgen-0.2.0-py3.8.egg/opentelemetry/semconv/main.py", line 64, in main
    semconv = parse_semconv(args, parser)
  File "/usr/local/lib/python3.8/site-packages/semconvgen-0.2.0-py3.8.egg/opentelemetry/semconv/main.py", line 35, in parse_semconv
    semconv.finish()
  File "/usr/local/lib/python3.8/site-packages/semconvgen-0.2.0-py3.8.egg/opentelemetry/semconv/model/semantic_convention.py", line 311, in finish
    fixpoint_inc = self.resolve_include(semconv)
  File "/usr/local/lib/python3.8/site-packages/semconvgen-0.2.0-py3.8.egg/opentelemetry/semconv/model/semantic_convention.py", line 450, in resolve_include
    raise ValidationError.from_yaml_pos(
opentelemetry.semconv.model.exceptions.ValidationError: Semantic Convention faas_span.http includes http.server but the latter cannot be found! - @87:5
make: *** [table-generation] Error 1
```

**Comment by anuraaga** [comment]
I think you need to `docker pull otel/semconvgen` - it would probably be good for the Makefile to pull to reduce gotchas for users.

**Comment by Oberon00** [comment]
We use a fixed version tag for the check, we need to do the same for the makefile.
Also, it seems that the semconvgen check is not included in `make check`? Which may make sense from a GitHub action perspective but not for users using the makefile locally.
